-- MySQL Script generated by MySQL Workbench
-- Thu Jan  1 09:53:19 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stockbroker
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stockbroker` ;

-- -----------------------------------------------------
-- Schema stockbroker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stockbroker` DEFAULT CHARACTER SET utf8 ;
USE `stockbroker` ;

-- -----------------------------------------------------
-- Table `stockbroker`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stockbroker`.`user` ;

CREATE TABLE IF NOT EXISTS `stockbroker`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `passwd` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iu_usr_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stockbroker`.`tax_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stockbroker`.`tax_group` ;

CREATE TABLE IF NOT EXISTS `stockbroker`.`tax_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ref_table` CHAR(3) NOT NULL,
  `ref_id` INT NOT NULL,
  `total` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stockbroker`.`broker_invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stockbroker`.`broker_invoice` ;

CREATE TABLE IF NOT EXISTS `stockbroker`.`broker_invoice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usr_id` INT NOT NULL,
  `tgr_id` INT NOT NULL,
  `filepath` VARCHAR(255) NOT NULL,
  `number` VARCHAR(32) NOT NULL,
  `trade_date` DATE NOT NULL,
  `settle_date` DATE NOT NULL,
  `total_bought` DECIMAL(10,2) NOT NULL,
  `total_sold` DECIMAL(10,2) NOT NULL,
  `raw_value` DECIMAL(10,2) NOT NULL COMMENT 'Sum of bought plus sold not including taxes.',
  `total_tax` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ixfk_biv_usr` (`usr_id` ASC) VISIBLE,
  INDEX `ixfk_biv_tgr` (`tgr_id` ASC) VISIBLE,
  CONSTRAINT `fk_biv_usr`
    FOREIGN KEY (`usr_id`)
    REFERENCES `stockbroker`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_biv_tgr`
    FOREIGN KEY (`tgr_id`)
    REFERENCES `stockbroker`.`tax_group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stockbroker`.`tax`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stockbroker`.`tax` ;

CREATE TABLE IF NOT EXISTS `stockbroker`.`tax` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(10) NOT NULL,
  `rate` DOUBLE NULL,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iu_tax_code` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stockbroker`.`tax_instance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stockbroker`.`tax_instance` ;

CREATE TABLE IF NOT EXISTS `stockbroker`.`tax_instance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tgr_id` INT NOT NULL,
  `tax_id` INT NOT NULL,
  `value` DOUBLE NOT NULL,
  `base_value` DOUBLE NULL,
  `tax_rate` DOUBLE NULL,
  PRIMARY KEY (`id`),
  INDEX `ixfk_tin_tgr` (`tgr_id` ASC) VISIBLE,
  INDEX `ixfk_tin_tax` (`tax_id` ASC) VISIBLE,
  CONSTRAINT `fk_tin_tgr`
    FOREIGN KEY (`tgr_id`)
    REFERENCES `stockbroker`.`tax_group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tin_tax`
    FOREIGN KEY (`tax_id`)
    REFERENCES `stockbroker`.`tax` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stockbroker`.`asset_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stockbroker`.`asset_class` ;

CREATE TABLE IF NOT EXISTS `stockbroker`.`asset_class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(32) NOT NULL,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iu_acs_code` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stockbroker`.`asset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stockbroker`.`asset` ;

CREATE TABLE IF NOT EXISTS `stockbroker`.`asset` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `acs_id` INT NOT NULL,
  `symbol` VARCHAR(32) NOT NULL,
  `desc` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ixfk_ast_acs` (`acs_id` ASC) VISIBLE,
  UNIQUE INDEX `iu_ast_symb` (`symbol` ASC) VISIBLE,
  CONSTRAINT `fk_ast_acs`
    FOREIGN KEY (`acs_id`)
    REFERENCES `stockbroker`.`asset_class` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stockbroker`.`broker_invoice_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stockbroker`.`broker_invoice_item` ;

CREATE TABLE IF NOT EXISTS `stockbroker`.`broker_invoice_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `biv_id` INT NOT NULL,
  `ast_id` INT NOT NULL,
  `tgr_id` INT NOT NULL,
  `order` INT NOT NULL,
  `bs_bit` TINYINT(1) NOT NULL,
  `qty` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `total` DOUBLE NOT NULL,
  `total_tax` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ixfk_bii_biv` (`biv_id` ASC) VISIBLE,
  INDEX `ixfk_bii_ast` (`ast_id` ASC) VISIBLE,
  INDEX `ixfk_bii_tgr` (`tgr_id` ASC) VISIBLE,
  UNIQUE INDEX `iu_bii_ord` (`id` ASC, `order` ASC) VISIBLE,
  CONSTRAINT `fk_bii_biv`
    FOREIGN KEY (`biv_id`)
    REFERENCES `stockbroker`.`broker_invoice` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bii_ast`
    FOREIGN KEY (`ast_id`)
    REFERENCES `stockbroker`.`asset` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bii_tgr`
    FOREIGN KEY (`tgr_id`)
    REFERENCES `stockbroker`.`tax_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stockbroker`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stockbroker`.`role` ;

CREATE TABLE IF NOT EXISTS `stockbroker`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(32) NOT NULL,
  `desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iu_role_code` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stockbroker`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stockbroker`.`user_role` ;

CREATE TABLE IF NOT EXISTS `stockbroker`.`user_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usr_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ixfk_uro_usr` (`usr_id` ASC) VISIBLE,
  INDEX `ixfk_uro_role` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_uro_usr`
    FOREIGN KEY (`usr_id`)
    REFERENCES `stockbroker`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_uro_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `stockbroker`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stockbroker`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stockbroker`.`permission` ;

CREATE TABLE IF NOT EXISTS `stockbroker`.`permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(32) NOT NULL,
  `desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `iu_perm_code` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stockbroker`.`role_perm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stockbroker`.`role_perm` ;

CREATE TABLE IF NOT EXISTS `stockbroker`.`role_perm` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `perm_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ixfk_rpm_role` (`role_id` ASC) VISIBLE,
  INDEX `ixfk_rpm_perm` (`perm_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_perm_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `stockbroker`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_perm_permission1`
    FOREIGN KEY (`perm_id`)
    REFERENCES `stockbroker`.`permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
